export type Member = {
  noAnggota: string;
  nip: string;
  idDigital: string;
  namaunit: string;
  namasub: string;
  keterangan: string;
  namaAnggota: string;
  alamat: string;
  telp: string;
  kelamin: string;
  kodebank: string;
  cabang: string;
  norek: string;
  namarek: string;
  saldoVoucher: number;
  saldoSimpanan: number;
  saldoSimpananSukarela: number;
  saldoPinjaman: number;
  nilaiAngsuran: number;
  pokokTerbayar: number;
  sisaPokok: number;
  // noAnggota: string;
  // firstName: string;
  // lastName: string;
  // email: string;
  // phone: string;
  // NIP: string;
  // memberTypeId: number;
  // unitId: number;
  // subUnitId: number;
  // voucherAmount: number;
};
